### ISSUE TITLE
'svgnative/SVGDocument.h' file not found error when installing via CocoaPods

### ISSUE THREAD

**Issue by AndreiArdelean1** [SDWebImage/SDWebImageSVGNativeCoder#1]
After adding SDWebImageSVGNativeCoder to the Podfile, the project fails to compile with `'svgnative/SVGDocument.h' file not found`. The svgnative pod was also added in the Pod project.

Adding `${PODS_ROOT}/svgnative/svg-native-viewer/svgnative/include/**` to `HEADER_SEARCH_PATHS` fixed this issue.

**Comment by WoodyHang** [comment]
Hello, according to your approach, my Xcode still reports an error: 'svgnative/SVGDocument.h' file not found

**Comment by dreampiggy** [comment]
Maybe I need to hack CocoaPods as well....🙃🙃🙃


I think I tested current CocoaPods integration works for

```
install! :generate_multiple_pod_projects => true
```

Actually I don't even test without this options (because I think this is the only way that CocoaPods should works.

--- 

Put all Pods into same project with different target, violate the Xcode build system structure, which has a HeaderMap thing)

That `project-all-headers.hmap` will map all your multiple targets in the same leve, which means, if you:

```
- Target1:
-   Foo.h
- Target2:
-   Foo.h
- Target3:
-   Bar.h (#import Foo.h)
```

This will cause undefined behavior which of `Foo.h` get imported. This is the case of that `HeaderMap`

**Comment by dreampiggy** [comment]
Anyway, just fix as you says, hope there are no more issues than it been fixed.

See #4
